//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Address
{
	public virtual string firstLine
	{
		get;
		set;
	}

	public virtual string secondLine
	{
		get;
		set;
	}

	public virtual string postCode
	{
		get;
		set;
	}

	public virtual string city
	{
		get;
		set;
	}

}

