//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Cook
{
	public virtual string firstName
	{
		get;
		set;
	}

	public virtual string lastName
	{
		get;
		set;
	}

    public virtual string email
    {
        get;
        set;
    }

	public virtual Address address
	{
		get;
		set;
	}

	public virtual string cookPreferences
	{
		get;
		set;
	}

	public virtual string travelMethod
	{
		get;
		set;
	}

    public virtual string password
    {
        get;
        set;
    }

	public virtual PVG pvg
	{
		get;
		set;
	}

	public virtual FoodHygieneCertificate foodHygiene
	{
		get;
		set;
	}

	public virtual Eater Eater
	{
		get;
		set;
	}

	public virtual IEnumerable<MealShare> MealShare
	{
		get;
		set;
	}

	public virtual MealSharesList MealSharesList
	{
		get;
		set;
	}

	public virtual void signUp()
	{
		throw new System.NotImplementedException();
	}

	public virtual void selectEater()
	{
		throw new System.NotImplementedException();
	}

}

