//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Eater
{
	public virtual string firstName
	{
		get;
		set;
	}

	public virtual string lastName
	{
		get;
		set;
	}

    public virtual string email
    {
        get;
        set;
    }

    public virtual Address address
	{
		get;
		set;
	}
    public virtual string foodPreferences
    {
        get;
        set;
    }
    public virtual string password
    {
        get;
        set;
    }

    public virtual FriendsAndFamilyDetails friendsAndFamily
    {
        get;
        set;
    }

    public virtual MealSharesList MealSharesList
	{
		get;
		set;
	}

	public virtual MealShare MealShare
	{
		get;
		set;
	}

	public virtual void signUp()
	{
		throw new System.NotImplementedException();
	}

	public virtual void selectFriendsAndFamily()
	{
		throw new System.NotImplementedException();
	}
    public override string ToString()
    {
        string output = firstName + " " + lastName + " " + address.postCode + " " + foodPreferences;
        return output;
    }

}

