//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FoodHygieneCertificate
{
    public virtual DateTime notifyDate { get; set; }

	public virtual string status
	{
        //values: OK, renewal within 3 months, none
		get;
		set;
	}
    public virtual string scan
    {
        // this is a string temporarilly saving the file name but needs
        // to store an image in the future
        get;
        set;
    }
    public virtual DateTime approvalDate
	{
		get;
		set;
	}


	public virtual DateTime renewIn3Months()
	{
		notifyDate = approvalDate.AddYears(3);
        notifyDate.AddMonths(-3);        
        return notifyDate;
        throw new System.NotImplementedException();
    }

}

