//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FriendsAndFamilyDetails
{
	public virtual string name
	{
		get;
		set;
	}

	public virtual string phone
	{
		get;
		set;
	}

	public virtual string email
	{
		get;
		set;
	}

	public virtual Eater Eater
	{
		get;
		set;
	}

	public virtual MealShare MealShare
	{
		get;
		set;
	}

	public virtual void notifyAboutMealShare()
	{
		throw new System.NotImplementedException();
	}

	public virtual void viewCookDetails()
	{
		throw new System.NotImplementedException();
	}

}

