//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MealShare
{
	public virtual Cook cook
	{
		get;
		set;
	}

	public virtual Eater eater
	{
		get;
		set;
	}

	public virtual DateTime date
	{
		get;
		set;
	}

	public virtual MealSharesList MealSharesList
	{
		get;
		set;
	}

	public virtual void uploadPicture()
	{
		throw new System.NotImplementedException();
	}

	public virtual void postComment()
	{
		throw new System.NotImplementedException();
	}

}

