//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MealSharesList
{
	public virtual MealShare mealShares
	{
		get;
		set;
	}

	public virtual void viewMealShare()
	{
		throw new System.NotImplementedException();
	}

	public virtual void addMealShare()
	{
		throw new System.NotImplementedException();
	}

	public virtual void sortList()
	{
		throw new System.NotImplementedException();
	}

}

