//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PVG
{
	public virtual string status
	{
        //values: OK/ Awaiting Result/ Rejected
		get;
		set;
	}

    public virtual string scan
    {
        // this is a string temporarilly saving the file name but needs
        // to store an image in the future
        get;
        set;
    }
}

